name: E2E Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        python-version: [3.9]

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust

      redis:
        image: redis:6.2-alpine
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - run: yarn install --prefer-offline
    - run: yarn build
    - run: cp e2e/e2e.yml .config/default.yml
    - run: yarn migrateandstart &

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pip install
      run: pip install -r requirements.txt
      working-directory: ./e2e

    - name: Setup playwright
      run: python -m playwright install
      working-directory: ./e2e

    - name: Run E2E Test
      run: pytest run.py --maxfail=1
      working-directory: ./e2e
    
    - name: Upload E2E ScreenShots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ScreenShots-${{ matrix.node-version }}
        path: e2e/ScreenShots
